[project]
name = "leetcode-problems"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
python_files = [
    "test_*.py",
    "__tests__/*.py"
]
pythonpath = [
    "src/disjoint-sets-union-find"
]
